import {
  createJWKManager,
  createJWKS,
  createJWKSManager,
  KeyStore,
  packBody,
  unpackBody,
} from '../src';

import { privateJWKS } from './fixture/private_jwks';
import { publicJWKS } from './fixture/public_jwks';

// Vectors generated by node-jose 2.2.0 on 2026-07-30 using the same 2048-bit RSA key pair
// as the test fixtures — ground truth for cross-version JWE compatibility.
const COMPAT_PLAINTEXT = '{"migratedFrom":"node-jose","version":"compat-test"}';

// node-jose token WITH zip=DEF (its default): jose v6 supports DEFLATE and decrypts this.
const NODE_JOSE_ZIP_TOKEN =
  'eyJ6aXAiOiJERUYiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAiLCJraWQiOiJLSUJBTkEifQ.Kx5YxeXrmHwFWblBMaq02bo_v-s110AwT-3MCmiAJMnYey6BLn4V_EGkZ9lMC61Tv8DCsUMTeJUd9fWoMGI-aaocuxaOzubrRsLUZ91ASg7HG6A_PwwJL4x_qMP-A0XsmiwrelGL0yYw3ev6U510S6MJ7qI4Gi-iuo5Y9J9a-hqs0YjtBVamY6nrle6eTimmVGRFeIZ-pIDPl_tenP-IpY5XmpPCYO9StFw8jeOTDrd1CIRVlxXAMqmwr1FjpZ7thOMOw5lsWh2QeYD1UnjRa7LrjM6yhSPK_bfgVEYPEFaMLGBrLNowURHRpIWd2gpFSX_pOXzfb8PgwMXzhYC_qw.Uy1qM7oB4vqL86aZ5L9Cow.A0xFHxMzfeTNYsNW1hWjcJ2aoUpiXETu4u9ufkkv8CY1R541LG-oPcHzMk6jxTN25jhSeUwwwYk2odUYrxMhsg.grNax6czYHGlGh-wUnlUpw'; // tslint:disable-line

// node-jose token WITHOUT zip: RSA-OAEP + A128CBC-HS256, no compression.
const NODE_JOSE_NO_ZIP_TOKEN =
  'eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAiLCJraWQiOiJLSUJBTkEifQ.nk9Xep8dScMJ2nczsuh6qctcMBKYj3lbBWGeNDza5mVjy3Inr34m3kou2nUGUxsilUGXc3mTq98RQj_9e4kPT6FO0nc8muwubWuSokRP0jzBx_1567DU2o9w-kQM0GT7P_pB4demLxuH-B6_QbnnzzvF3XZ7HK0FO4Z8xlfgaUGc6o8-7AwYBTI3bzTktLvgObnpCboDQKNIByI5krLKeCLqQAsG9EMNWljqe7YqX5-ZExa5-VZVH3hPSMyAXCvOcR-JTcWUPcS7z-03b3xJjnZnyhJpFEBxYf2oaWMtU3_dLaxvs9yrmMaKwtGVLznJYQzdBCHuDD4P-DY0mxFoMA.YdNY-HBbOl3e9BU_7PV2Tw.i2fN1HKzU4icUj9gWCjAhzW1Lrwvwut5JbhZNYzTjSMwmb0CHNENtFKfkeIAS45uAU1vFWlMlhZUftWXD0BfGg.W-3RmeRvR9gopHrJdWeiAA'; // tslint:disable-line

// Produced by node-jose's util.base64url.encode(JSON.stringify({encryptedAESKey, encryptedPayload}), 'utf8')
const NODE_JOSE_PACKED_BODY =
  'eyJlbmNyeXB0ZWRBRVNLZXkiOiJzZW50aW5lbC1hZXMta2V5LWZvci1wYWNrLXRlc3QiLCJlbmNyeXB0ZWRQYXlsb2FkIjoic2VudGluZWwtZW5jcnlwdGVkLXBheWxvYWQifQ'; // tslint:disable-line
const SENTINEL_AES_KEY = 'sentinel-aes-key-for-pack-test';
const SENTINEL_ENCRYPTED_PAYLOAD = 'sentinel-encrypted-payload';

describe('Migration compatibility — node-jose v2 → jose v6', () => {
  describe('packBody / unpackBody wire format', () => {
    it('packBody produces byte-identical output to node-jose util.base64url.encode', () => {
      expect(packBody(SENTINEL_AES_KEY, SENTINEL_ENCRYPTED_PAYLOAD)).to.equal(
        NODE_JOSE_PACKED_BODY
      );
    });
    it('unpackBody correctly parses a body that was packed by node-jose', () => {
      const { encryptedAESKey, encryptedPayload } = unpackBody(NODE_JOSE_PACKED_BODY);
      expect(encryptedAESKey).to.equal(SENTINEL_AES_KEY);
      expect(encryptedPayload).to.equal(SENTINEL_ENCRYPTED_PAYLOAD);
    });
  });

  describe('cross-version JWE decryption — zip:DEF (node-jose default)', () => {
    it('decrypts a zip-compressed token produced by node-jose', async () => {
      const manager = await createJWKManager(privateJWKS);
      const result = await manager.decrypt(NODE_JOSE_ZIP_TOKEN);
      expect(result.payload.toString('utf8')).to.equal(COMPAT_PLAINTEXT);
      expect(result.plaintext.toString('utf8')).to.equal(COMPAT_PLAINTEXT);
    });
    it('payload and plaintext are both Buffers', async () => {
      const manager = await createJWKManager(privateJWKS);
      const result = await manager.decrypt(NODE_JOSE_ZIP_TOKEN);
      expect(Buffer.isBuffer(result.payload)).to.equal(true);
      expect(Buffer.isBuffer(result.plaintext)).to.equal(true);
    });
    it('header matches the protected header fields that node-jose encoded', async () => {
      const manager = await createJWKManager(privateJWKS);
      const result = await manager.decrypt(NODE_JOSE_ZIP_TOKEN);
      expect(result.header).to.eql({
        zip: 'DEF',
        enc: 'A128CBC-HS256',
        alg: 'RSA-OAEP',
        kid: 'KIBANA',
      });
    });
  });

  describe('cross-version JWE decryption — no zip', () => {
    it('decrypts a node-jose token without zip compression', async () => {
      const manager = await createJWKManager(privateJWKS);
      const result = await manager.decrypt(NODE_JOSE_NO_ZIP_TOKEN);
      expect(result.payload.toString('utf8')).to.equal(COMPAT_PLAINTEXT);
    });
    it('header has no zip field', async () => {
      const manager = await createJWKManager(privateJWKS);
      const result = await manager.decrypt(NODE_JOSE_NO_ZIP_TOKEN);
      expect(result.header).to.eql({ enc: 'A128CBC-HS256', alg: 'RSA-OAEP', kid: 'KIBANA' });
    });
  });

  describe('new token format', () => {
    it('tokens produced by encrypt carry zip:DEF header — wire-compatible with node-jose', async () => {
      const manager = await createJWKManager(publicJWKS);
      const token = await manager.encrypt('KIBANA', Buffer.from('hello', 'utf8'));
      const header = JSON.parse(Buffer.from(token.split('.')[0], 'base64url').toString('utf8'));
      expect(header.zip).to.equal('DEF');
      expect(header.enc).to.equal('A128CBC-HS256');
      // Key wrap is the one deliberate wire change: RSA-OAEP (SHA-1) → RSA-OAEP-256, for FIPS
      // 140-3. node-jose can decrypt this too, as long as the receiving key is not pinned to
      // RSA-OAEP by its JWK "alg" member — see key-wrap.spec.ts and
      // docs/rsa-oaep-256-migration.md.
      expect(header.alg).to.equal('RSA-OAEP-256');
      expect(header.kid).to.equal('KIBANA');
    });
  });

  describe('JWKSManager.store is a KeyStore instance', () => {
    it('store property is typed as KeyStore (was any in node-jose version)', async () => {
      const manager = await createJWKSManager(privateJWKS);
      expect(manager.store).to.be.instanceOf(KeyStore);
    });
  });

  describe('createJWKS', () => {
    it('returns an empty KeyStore when called with no arguments', async () => {
      const store = await createJWKS();
      expect(store).to.be.instanceOf(KeyStore);
      expect(store.toJSON().keys).to.have.length(0);
    });
    it('loads private key entries — get and remove work against fixture JWKS', async () => {
      const store = await createJWKS(privateJWKS);
      expect(store.get('KIBANA')).to.not.equal(undefined);
      store.remove(privateJWKS.keys[0]);
      expect(store.get('KIBANA')).to.equal(undefined);
    });
    it('rejects a malformed JWK at load time rather than on first use', async () => {
      // Missing the modulus. The exact message comes from the platform's WebCrypto, so only the
      // fail-fast behaviour is asserted.
      const malformed = { kty: 'RSA', kid: 'BROKEN', use: 'enc', alg: 'RSA-OAEP', e: 'AQAB' };
      let threw = false;
      try {
        await createJWKS({ keys: [malformed as any] });
      } catch (err) {
        threw = true;
      }
      expect(threw).to.equal(true);
    });
  });
});
